// <auto-generated />
using ControleFolhaPagamento.Aplicacao.Infraestrutura.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ControleFolhaPagamento.Aplicacao.Migrations
{
    [DbContext(typeof(GlobalContext))]
    [Migration("20210520014818_Criacao_tabela_funcionarios")]
    partial class Criacao_tabela_funcionarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ControleFolhaPagamento.Aplicacao.Dominio.Entidades.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Documento")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<bool>("PossuiPlanoDental")
                        .HasColumnType("boolean");

                    b.Property<bool>("PossuiPlanoSaude")
                        .HasColumnType("boolean");

                    b.Property<bool>("PossuiValeTransporte")
                        .HasColumnType("boolean");

                    b.Property<double>("SalarioBruto")
                        .HasColumnType("double precision");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<string>("SobreNome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
